PanDAWMS/panda-harvester

pandaharvester/harvestermonitor/htcondor_monitor.py
Fix bug of HTCondor module when monitoring Condor-C jobs.
=> Fix htcondor monitor

pandaharvester/harvestercore/db_proxy.py, pandaharvester/harvestermonitor/cobalt_monitor.py, pandaharvester/harvestersubmitter/cobalt_submitter.py, pandaharvester/harvestertest/getJobs.py, pandaharvester/harvestertest/read_shared_file_messenger_files.py
first part - add ALCF cobalt scheduler code add submitter and monitor for cobalt submitter at ALCF
add file to get the listing of jobs from db_proxy in test directory
add file to print the files created by the shared file system messenger - user adds the location to look for these files
final file is db_proxy.py - remove print statement from get_jobs()
=> add ALCF cobalt scheduler code

pandaharvester/harvestermover/mover_utils.py, pandaharvester/harvesterpreparator/pilotmover_preparator.py, pandaharvester/harvesterpreparator/rse_direct_preparator.py, pandaharvester/harvesterstager/rucio_stager.py
remove unused dataset_name input variable.
=> remove superfluous input variable from construct_file_path function

pandaharvester/harvestersubmitter/dummy_submitter.py, pandaharvester/harvestersubmitter/saga_submitter.py, pandaharvester/harvestertest/submitterTest.py, pandaharvester/harvesterworkermaker/simple_worker_maker.py
Fixes in dummy_sumitter and simple_worker_maker.  
This iteration with basic functionality validated with 'simple_worker_maker' and compatible with 'dummy_monitor'.  
SAGA-PYTHON package should be deployed to be able to use this submitter. http://saga-python.readthedocs.io/en/latest/
=> SAGA submitter for simple payload. 

pandaharvester/harvestermonitor/saga_monitor.py, pandaharvester/harvestersubmitter/saga_submitter.py
SAGA monitor, basic functionality
=> OLCF validation

pandaharvester/harvestermonitor/cobalt_monitor.py, pandaharvester/harvesterstager/rucio_stager_hpc.py
add file to stage out files via rucio
make changes to cobalt_monitor.py to use jobReport.json
=> add rucio_stager_hpc to repo

pandaharvester/harvesterstager/rucio_stager_hpc.py
remove debugging print statements from rucio_stager_hpc.py routines
=> remove print statements

pandaharvester/harvestermessenger/shared_file_messenger.py
change shared_file_messenger to protect against malformed json files.
=> add protection against malformed Output file name json file

pandaharvester/harvestercore/communicator.py, pandaharvester/harvestertest/TestCommunication.py
create a simple test script for communicator and fix return information in check_panda ftn
=> create a simple test script for communicator and fix return information in check_panda ftn

pandaharvester/harvesterstager/rucio_stager_hpc.py
Added error handling to rucio stager so to avoid failing a transfer which failed with a rucio error in which a retry should be made. Also added some debug statements.
=> rucio stager patch

pandaharvester/harvestersweeper/cobalt_sweeper.py
Copy of the condor sweeper, but with cobalt.
=> adding cobalt sweeper

pandaharvester/harvesterstager/go_stager.py
remove print statements - go_preparator - initial commit of go_stager
=> remove print statements - go_preparator - initial commit of go_stager

pandaharvester/harvestertest/worker_pandajob_dump.py
Hi, here is my monitoring script for posterity.
=> Adding monitoring script

pandaharvester/harvesterstager/go_stager.py, pandaharvester/harvestertest/stageOutTest_globus.py
add new test routine for testing stage out of globus stager.
rework go_stager.py check_status function to search transfers by label and not globus task ID
=> globus stager update

pandaharvester/harvesterstager/go_bulk_stager.py, pandaharvester/harvestertest/stageOutTest_go_bulk_stager.py
Pull request for Globus Bulk Stager
=> Globus Bulk Stager

pandaharvester/harvestertest/dumpTable.py
=> routine dump job and file table

pandaharvester/harvestercore/job_spec.py, pandaharvester/harvestermisc/globus_utils.py, pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvesterpreparator/go_preparator.py, pandaharvester/harvesterstager/go_bulk_stager.py, pandaharvester/harvesterstager/go_stager.py
add changes to handling globus errors - now return error status (True or None) and error message depending on error.
This affects globus_utils.py,  go_preparator.py go_stager.py and go_bulk_stager.py
add new function to jobspec.py needed for new Globus bulk preparator. 
add new routine go_bulk_preparator.py
=> new addition of globus bulk preparator

pandaharvester/harvestermisc/globus_utils.py, pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvesterpreparator/go_preparator.py, pandaharvester/harvesterstager/go_bulk_stager.py, pandaharvester/harvesterstager/go_stager.py, pandaharvester/harvestertest/stageInTest_globus.py, pandaharvester/harvestertest/stageInTest_go_bulk_preparator.py, pandaharvester/harvestertest/stageOutTest_globus.py
Refactor globus_utils to move common globus code there. 
Fix associated routines according
=> refactor globus_utils code and further develop globus test code and bulk transfer code

pandaharvester/harvestertest/getQueuedata.py
code used for dump queue data information used by minipilot
=> initial python script to dump queuedata needed by miniPilot

pandaharvester/harvesterbody/master.py
Tested and it seems to work ok
=> Added isatty method to std error wrapper

pandaharvester/harvestermonitor/apfgrid_monitor.py, pandaharvester/harvestersubmitter/apfgrid_submitter.py, pandaharvester/harvestersweeper/apfgrid_sweeper.py
Single commit version. You mentioned 4 files. I only saw 3. What was the fourth?
=> Initial prototype of APF-based Harvester.

examples/htcondor_atlas-grid-ce_push.sdf.d/arc-ce.sdf, examples/htcondor_atlas-grid-ce_push.sdf.d/cream-ce.sdf, examples/htcondor_atlas-grid-ce_push.sdf.d/htcondor-ce.sdf, pandaharvester/harvestersubmitter/htcondor_submitter.py
=> Improve htcondor_submitter

pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvestertest/further_testing_go_bulk_preparator.py
add new file to further test globus bulk preparator 
make changes to go_bulk_preparator. py to reduce the amount of messages to the log files during debugging
=> globus bulk preparator modifications 

pandaharvester/harvesterpreparator/go_bulk_preparator.py
make changes to ensure db_lock is released or put in error log
and reduce once more the amount of information in debug log
=> make changes to ensure db_lock is released or put in error log

pandaharvester/harvesterbody/monitor.py, pandaharvester/harvestercore/work_spec.py
I still need this to avoid errors from monitor agent.
Maybe need not to merge this if there is a better solution.
Just leave a record about this issue here.
=> Fix issue when worker workAttributes is None

pandaharvester/harvestermessenger/apache_messenger.py, pandaharvester/harvestermessenger/http_server_messenger.py, setup.py, templates/init.d/panda_harvester-uwsgi.rpmnew.template, templates/panda_harvester-uwsgi.ini.rpmnew.template
=> Frontend response content fix & uwsgi option of config file

pandaharvester/harvestercredmanager/no_voms_cred_manager.py
The generation of the voms cert from grid cert didn't work for me without these options.
=> add required voms-proxy-init options

examples/htcondor_atlas-grid-ce_pull.sdf.d/arc-ce.sdf, examples/htcondor_atlas-grid-ce_pull.sdf.d/cream-ce.sdf, examples/htcondor_atlas-grid-ce_pull.sdf.d/htcondor-ce.sdf, pandaharvester/harvesterbody/worker_adjuster.py
(deepcopy to avoid runtime error)
=>  Fix worker_adjuster

pandaharvester/harvesterstager/go_bulk_stager.py
fix locking issue and reduce debug log size
=> fix locking problem and reduce debug log size

pandaharvester/harvesterstager/go_bulk_stager.py
add check for non valid transfer id
=> add check for non valid transfer id

pandaharvester/harvesterstager/go_bulk_stager.py
=> add import string

pandaharvester/harvesterstager/go_bulk_stager.py
=> fix typo in debug print statements

pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvesterstager/go_bulk_stager.py
=> "add panda for scope = None"

pandaharvester/harvestermessenger/arc_messenger.py, pandaharvester/harvestermisc/arc_utils.py, pandaharvester/harvestermonitor/arc_monitor.py, pandaharvester/harvestersubmitter/arc_parser.py, pandaharvester/harvestersubmitter/arc_submitter.py, pandaharvester/harvestersweeper/arc_sweeper.py, templates/panda_harvester.cfg.rpmnew.template
- handling of different proxies for prod/analy jobs
- download job log files to expose through local web server
- general updates for recent changes in harvester core
=> Updates to ARC plugins

installer/install-harvester.sh
The installer script I was presenting during the last WFMS meeting
=> Added installer for Harvester

pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvesterstager/go_bulk_stager.py
create unique dummy transfer id and reduce size of Debug log file.
=> create unique dummy transfer id

pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvesterstager/go_bulk_stager.py
change logic to catch holding transfer groups after harvester restart
=> change logic to catch holding transfer groups after harvester restart

pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvesterstager/go_bulk_stager.py
reduce size of debug log and fix indent
=> reduce size of debug log and fix indent

pandaharvester/commit_timestamp.py, pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvesterstager/go_bulk_stager.py
change to print out only 10 file attributes and fix counter bug
=> change to print out only 10 file attributes and fix counter bug 

pandaharvester/commit_timestamp.py, pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvesterstager/go_bulk_stager.py
add fix for case when all files are in ready state
=> add fix for case when all files are in ready state

pandaharvester/commit_timestamp.py, pandaharvester/harvesterstager/fts_stager.py, pandaharvester/harvesterstager/go_bulk_stager.py, pandaharvester/harvesterstager/go_stager.py, pandaharvester/harvesterstager/rse_direct_stager.py, pandaharvester/harvesterstager/rucio_stager.py, pandaharvester/harvesterstager/rucio_stager_hpc.py
file zp file creation to remove file paths from files added to zip file
=> fix zipfile 

installer/PYTHON-INSTALLATION.md, installer/README.md, pandaharvester/harvestercore/communicator.py
Added documentation and one update to communicator which allows to use non-pilot/production proxies with Harvester in case if it is properly configured on server side.
=> Installer docs and communicator update

pandaharvester/commit_timestamp.py, pandaharvester/harvesterpreparator/go_bulk_preparator.py, pandaharvester/harvesterstager/go_bulk_stager.py, pandaharvester/harvestertest/further_testing_go_bulk_preparator-test.py, pandaharvester/harvestertest/further_testing_go_bulk_stager.py
Add two new test routines to test go_bulk_preparator and go_bulk_stager plugins
ensure globus data transfer object is properly initialized in go_bulk_preparator
set the objstoreID for output files in go_bulk_stager needed for ES output
=> fix go_bulk_preparator go_bulk_stager and add new test routines

pandaharvester/commit_timestamp.py, pandaharvester/harvesterstager/go_bulk_stager.py
make changes for Yoda job to scope and objStoreID
=> make changes for Yoda job to scope and objStoreID

pandaharvester/harvestercore/db_proxy.py, pandaharvester/harvestercore/queue_config_mapper.py
Reverts PanDAWMS/panda-harvester#138
=> Revert "Auto initialization of UPS queue stats to panda server"

pandaharvester/harvesterbody/cacher.py, pandaharvester/harvestercore/communicator.py, pandaharvester/harvestercore/resource_type_mapper.py, pandaharvester/harvesterworkermaker/simple_worker_maker.py
Add support for HIMEM queues in UPS mode
=> Get resource types

pandaharvester/harvesterstager/go_rucio_stager.py
add include for QueueConfigMapper
=> add harvester QueueConfigMapper include

pandaharvester/commit_timestamp.py, pandaharvester/harvestercore/fifos.py, pandaharvester/harvestercore/queue_config_mapper.py, pandaharvester/harvestercore/spec_base.py, pandaharvester/harvesterscripts/queue_config_tool.py
Including some parts refactored. Please review
=> Add qconf validation

pandaharvester/harvesterstager/go_rucio_stager.py
need to add additional space to fix stager routine
=> fix indent typo

pandaharvester/harvesterbody/service_monitor.py, pandaharvester/harvesterbody/worker_adjuster.py, pandaharvester/harvestermisc/apfmon.py, pandaharvester/harvesterworkermaker/simple_worker_maker.py
Fixes for service monitoring and APF mon
=> Uwsgi service fix

pandaharvester/commit_timestamp.py, pandaharvester/harvestercloud/k8s_startup_script.py
We can try k8s secret credmanager no matter what, but I guess this also does the trick.
=> k8s: Unset proxyContent asap

pandaharvester/harvestermessenger/shared_file_messenger.py
Make change to put output files in a subdirectory of the droid working directory.
=> add output directory

pandaharvester/harvestermonitor/act_monitor.py, pandaharvester/harvestersubmitter/act_submitter.py
This change adds "submissionhost" and "nativestatus" information.
=> Adding extra monitoring info for aCT

templates/panda_harvester.cfg.rpmnew.template
aipanda156 was added to the list of submitters on central instance Harvesters: adding here for consistency
=> Add aipanda156 to list of submitters in cfg template
